'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Maze2._0.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Attack0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Attack0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Attack1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Attack1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Attack2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Attack2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Attack3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Attack3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Chest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chest", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fire0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fire0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fire1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fire1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fire2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fire2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fire3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fire3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Floor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Floor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WWWWWWWWWWW
        '''WFFFFFWFFFW
        '''WFTFFFWFTFW
        '''WFWCWFWFTFW
        '''WFFWFFWFTFW
        '''WFFWFFFFTFW
        '''WWFWWWWFTPW
        '''WFFFFFFTTFW
        '''WFWFWFTFTFW
        '''WCFFWFFFFFW
        '''WWWWWWWWWWW.
        '''</summary>
        Friend ReadOnly Property Level1() As String
            Get
                Return ResourceManager.GetString("Level1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WWWWWWWWWWWWWWWWWWWWWWWWWWWW
        '''WFFTTTTTTFTTTTTTTTTTTCTTTTTW
        '''WTTTTTTTTTTTTFTTTTTTTTTTTTTW
        '''WTTTCTTTTTTTTTTTTTTTFTTTTFFW
        '''WTTTTTTTTFTTTTCTTTTTTTTTTFPW
        '''WWWWWWWWWWWWWWWWWWWWWWWWWWWW.
        '''</summary>
        Friend ReadOnly Property Level2() As String
            Get
                Return ResourceManager.GetString("Level2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WWWWWWWWWWWWWWWWW
        '''WFFFWWTCFFWWFFFFW
        '''WFFFFFFFFFFFFFFFW
        '''WWWWWFFWWTTTWWWWW
        '''WWFFTTTFFFFWWFCFW
        '''WFFWWWWWWWTWWFWFW
        '''WTFFFWWWWWTFFFFFW
        '''WFFFFWWWWWTWWWWWW
        '''WFTFFFFFFFFFFFFPW
        '''WWWWWWWWWWWWWWWWW.
        '''</summary>
        Friend ReadOnly Property Level3() As String
            Get
                Return ResourceManager.GetString("Level3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WWWWWWWWWWWWWWWWWWWW
        '''WFFFTCTFFWWFFTTFCCWW
        '''WWWFFFFFWWWWFWFWWWWW
        '''WCFFTTWWWWWWFWFFTWWW
        '''WFFFWWWFFFWWWWWFFWWW
        '''WWWTWWWWWFWWWWFFFFWW
        '''WWWFFFFFFFWWWWFFFWWW
        '''WWWFWWTTTFWWWWFFWWWW
        '''WWWFWWWWFFFFFFFFWWWW
        '''WWWFWWFFFWWWWWWWWWPW
        '''WWWFFFFFFFFFFFFFFFFW
        '''WWWWWWWWWWWWWWWWWWWW.
        '''</summary>
        Friend ReadOnly Property Level4() As String
            Get
                Return ResourceManager.GetString("Level4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Portal0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Portal0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Portal1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Portal1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Portal2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Portal2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Trap0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Trap0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Trap1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Trap1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Trap2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Trap2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Trap3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Trap3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Wall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Wall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
